spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-preproject-16.ccgspdnar1fd.ap-northeast-2.rds.amazonaws.com:13306/test?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: admin
    password: 87654321

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
config:
  domain: http://pre16-s3-bucket.s3-website.ap-northeast-2.amazonaws.com

mail:
  address:
    admin: oneyang@gmail.com
jwt:
  key: ${JWT_SECRET_KEY}               # 민감한 정보는 시스템 환경 변수설정
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420
